name: Update README

on:
  schedule:
    # Run the workflow every 3 days at midnight UTC
    - cron: "0 0 */3 * *"

  # Allow manual triggering of the workflow
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run the update_readme.py script
    - name: Run script
      env:
        PYTHONPATH: ${{ github.workspace }}
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        REPO: ${{ secrets.REPO }}
        team_id: ${{ secrets.TEAM_ID }}
      run: |
        echo "Current working directory: $(pwd)"
        echo "PYTHONPATH=$PYTHONPATH"
        python src/update_readme.py
